capture_unit/cic_filter.sv
capture_unit/recorder_audio_pipeline.sv

synthesis_unit/adsr_modulator.sv
synthesis_unit/audio_mixer.sv
synthesis_unit/custom_wave_generator.sv
synthesis_unit/sine_wave_generator.sv
synthesis_unit/square_wave_generator.sv
synthesis_unit/triangle_wave_generator.sv
synthesis_unit/square_wave_generator.sv
synthesis_unit/audio_generation_pipeline.sv
synthesis_unit/audio_synthesis_pipeline.sv

intf/waveform_registers.sv
intf/ac_unit_registers.sv
intf/as_unit_registers.sv
intf/pcm2pdm_converter.sv
intf/pdm2pcm_converter.sv

audio_capture_unit.sv
audio_synthesis_unit.sv

apu.sv