// ============================================================================
// sim_cosim.cpp - Lockstep harness ApogeoRV (DUT) <-> Spike golden model
//
// 1. Verilator builds cosim_top: CPU complex + ROM/DDR/IO.
// 2. The same ELF is loaded into:
//    a) Spike RAM at 0x8000_0000.
//    b) DUT DDR/ROM through DPI: ddr_preload_word / rom_preload_word.
// 3. The clock advances. For each committed RTL instruction, the RTL calls
//    rvfi_commit() through DPI. The harness runs spike.step(1) for each event
//    and compares PC, rd, and memory access values.
// 4. The simulation stops at the first mismatch, printing diagnostics,
//    or at HTIF termination.
//
// ISA and privilege mode are passed from the Makefile through
// -DCOSIM_ISA and -DCOSIM_PRIV, derived from config.mk.
// CSR comparison is intentionally excluded.
// ============================================================================

#include <iostream>
#include <iomanip>
#include <cstdint>
#include <cstring>
#include <vector>
#include <deque>
#include <string>
#include <csignal>

#include "Vcosim_top.h"
#include "Vcosim_top__Dpi.h"
#include "verilated.h"
#include "verilated_fst_c.h"
#include "svdpi.h"

#include "riscv/cfg.h"
#include "riscv/sim.h"
#include "riscv/processor.h"
#include "riscv/mmu.h"
#include "riscv/disasm.h"
#include "riscv/trap.h"

#include "elf_loader.h"

// ============================================================================
//      GLOBAL STATE
// ============================================================================

static Vcosim_top      *dut = nullptr;
static VerilatedFstC   *tfp = nullptr;

static uint64_t sim_time = 0;

static bool enable_trace = true;

static constexpr uint64_t HALF_PERIOD_NS = 5;
static constexpr uint32_t USER_BASE = 0x80000000u;

// RVFI event generated by the RTL through DPI.
// One event is produced for each committed instruction.
struct RvfiEvent {
    bool     is_exception;
    uint32_t pc;
    uint32_t info;        // Instruction info vector
    uint32_t rd;
    uint32_t rd_value;
    bool     is_store;
    bool     is_load;
    uint32_t mem_addr;    // Absolute address, as used by cpu_store/load_channel
    uint32_t mem_data;    // Source register value, later masked according to width
    uint32_t mem_width;   // 0=BYTE, 1=HALF_WORD, 2=WORD
};

static std::deque<RvfiEvent> g_events;


// ============================================================================
//      DPI EXPORTS FROM RTL, called inside eval()
// ============================================================================

extern "C" void rvfi_commit(uint32_t is_exception, uint32_t pc, uint32_t info,
                            uint32_t rd, uint32_t rd_value,
                            uint32_t is_store, uint32_t is_load,
                            uint32_t mem_addr, uint32_t mem_data,
                            uint32_t mem_width) {
    g_events.push_back(RvfiEvent{
        is_exception != 0, pc, info, rd, rd_value,
        is_store != 0, is_load != 0, mem_addr, mem_data, mem_width
    });
}


// ============================================================================
//      CLOCK / RESET
// ============================================================================

static void dump_trace() {
    if (tfp) tfp->dump(sim_time);
}

static void clk_tick() {
    dut->clk = 1;
    dut->eval();
    dump_trace();
    Verilated::timeInc(HALF_PERIOD_NS);
    sim_time += HALF_PERIOD_NS;

    dut->clk = 0;
    dut->eval();
    dump_trace();
    Verilated::timeInc(HALF_PERIOD_NS);
    sim_time += HALF_PERIOD_NS;
}

static void reset_dut() {
    dut->rst_n = 0;
    for (int i = 0; i < 8; i++) clk_tick();
    dut->rst_n = 1;
    clk_tick();
}


// ============================================================================
//      CLEANUP
// ============================================================================

static void close_and_exit(int code) {
    if (tfp) { tfp->close(); delete tfp; tfp = nullptr; }
    if (dut) { delete dut; dut = nullptr; }
    std::exit(code);
}

static void signal_handler(int s) {
    std::cout << "\n[COSIM] signal " << s << std::endl;
    close_and_exit(128 + s);
}


// ============================================================================
//      DIAGNOSTICS
// ============================================================================

static std::deque<uint32_t> g_pc_history;

static void push_pc(uint32_t pc) {
    g_pc_history.push_back(pc);
    if (g_pc_history.size() > 8) g_pc_history.pop_front();
}

static void report_mismatch(uint64_t retire, const char* what,
                            const RvfiEvent& d,
                            uint32_t spike_pc, uint32_t spike_rd,
                            uint32_t spike_val,
                            disassembler_t* dis, insn_t insn) {
    std::cout << std::hex << std::setfill('0');
    std::cout << "\n[COSIM][MISMATCH] @retire #" << std::dec << retire
              << std::hex << " (" << what << ")\n";
    std::cout << " instr : " << dis->disassemble(insn) << "\n";
    std::cout << " PC    : DUT 0x" << std::setw(8) << d.pc
              << " | SPIKE 0x" << std::setw(8) << spike_pc << "\n";

    if (d.rd != 0 || spike_rd != 0) {
        std::cout << " rd    : DUT x" << std::dec << d.rd
                  << " <= 0x" << std::hex << std::setw(8) << d.rd_value
                  << " | SPIKE x" << std::dec << spike_rd
                  << " <= 0x" << std::hex << std::setw(8) << spike_val << "\n";
    }

    if (d.is_store || d.is_load) {
        std::cout << " mem   : DUT " << (d.is_store ? "ST" : "LD")
                  << " @0x" << std::setw(8) << d.mem_addr
                  << " data 0x" << std::setw(8) << d.mem_data << "\n";
    }

    std::cout << " last PCs : ";
    for (auto p : g_pc_history)
        std::cout << std::hex << std::setw(8) << p << " ";
    std::cout << std::dec << "\n";

    if (enable_trace)
        std::cout << " waveform : cosim/out/cosim.fst\n";

    std::cout << "[COSIM] FAIL\n";
}


// ============================================================================
//      MAIN
// ============================================================================

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    std::string fw_path   = "cosim/out/firmware.elf";
    std::string boot_path = "cosim/out/boot.elf";
    uint64_t max_retire = UINT64_MAX;

    for (int i = 1; i < argc; i++) {
        std::string a(argv[i]);

        if      (a.rfind("+firmware=", 0) == 0)     fw_path = a.substr(10);
        else if (a.rfind("+boot=", 0) == 0)         boot_path = a.substr(6);
        else if (a == "+notrace")                   enable_trace = false;
        else if (a.rfind("+max_retire=", 0) == 0)   max_retire = std::stoull(a.substr(12));
    }

    dut = new Vcosim_top;

    if (enable_trace) {
        Verilated::traceEverOn(true);
        tfp = new VerilatedFstC;
        dut->trace(tfp, 99);

        tfp->open("out/cosim.fst");
    }


    // Load ELF:
    // - User sections, >= 0x8000_0000, go to DUT DDR using a relative base.
    // - Boot sections, < 0x4000, go to DUT ROM.
    // Spike receives the full image through HTIF, below.
    ElfImage img;
    
    if (!load_elf(fw_path, img)) {
        std::cerr << "[COSIM] cannot load ELF: " << fw_path << std::endl;
        return 2;
    }

    // DPI exported functions live in the scope of the modules that contain them:
    // cosim_top.ddr for ddr_preload_word and cosim_top.boot_rom for
    // rom_preload_word. Retrieve both scopes explicitly.
    auto get_scope = [](const char* a, const char* b) -> svScope {
        svScope s = svGetScopeFromName(a);
        if (!s) s = svGetScopeFromName(b);
        return s;
    };

    svScope ddr_scope = get_scope("TOP.cosim_top.ddr",      "cosim_top.ddr");
    svScope rom_scope = get_scope("TOP.cosim_top.boot_rom", "cosim_top.boot_rom");

    if (!ddr_scope || !rom_scope) {
        std::cerr << "[COSIM] FATAL: DPI scope not found (ddr=" << ddr_scope
                  << " rom=" << rom_scope << ")\n";
        return 4;
    }

    // Program user image into DUT DDR using DDR-relative addresses.
    for (const auto& seg : img.words) {
        uint32_t addr = seg.first, data = seg.second;

        if (addr >= USER_BASE) {
            svSetScope(ddr_scope);
            ddr_preload_word(addr - USER_BASE, data);   // DPI export from cosim_ddr
        } else if (addr < 0x4000) {
            svSetScope(rom_scope);
            rom_preload_word(addr, data);               // Optional boot sections in user ELF
        }
    }


    ElfImage boot;

    if (load_elf(boot_path, boot)) {
        svSetScope(rom_scope);

        for (const auto& seg : boot.words) {
            if (seg.first < 0x4000)
                rom_preload_word(seg.first, seg.second);
        }

        std::cout << "[COSIM] boot stub loaded into ROM from " << boot_path << "\n";
    } else {
        std::cout << "[COSIM] WARN: boot stub missing (" << boot_path
                  << "); core will start from ROM[0]=0\n";
    }


    // ------------------------------------------------------------------------
    // Spike golden model
    // ------------------------------------------------------------------------

    cfg_t cfg;
    cfg.isa  = COSIM_ISA;     // From config.mk through -DCOSIM_ISA
    cfg.priv = COSIM_PRIV;    // From config.mk through -DCOSIM_PRIV

    std::vector<std::pair<reg_t, abstract_mem_t*>> mems;
    mems.push_back(std::make_pair((reg_t)USER_BASE, new mem_t(256 * 1024 * 1024)));

    debug_module_config_t dm_config;
    std::vector<std::pair<const device_factory_t*, std::vector<std::string>>> plugins;
    std::vector<std::string> htif_args;
    htif_args.push_back(fw_path);

    sim_t spike(&cfg, false, mems, plugins, false, htif_args, dm_config,
                nullptr, false, nullptr, false, nullptr, std::nullopt);

    processor_t* p = spike.get_core(0);
    state_t* st = p->get_state();

    // Enable the commit log, needed to extract Spike load/store addresses and
    // compare them against the core writeback information.
    p->enable_log_commits();

    // Load firmware into Spike memory manually. htif_t::load_program() is called
    // only by spike.run(); since run() is not used, preload all ELF words
    // through memif().write().
    for (const auto& seg : img.words) {
        uint32_t addr = seg.first, data = seg.second;
        spike.memif().write(addr, 4, &data);
    }

    // The DUT executes the ROM stub:
    // Spike has no RAM at 0x0, so it starts directly from the ELF entry.
    // The harness discards DUT retires with PC < USER_BASE and aligns the
    // comparison from the first user retire, matching Spike entry.
    st->pc = img.entry;

    auto isa_p = p->get_isa();
    disassembler_t dis(&isa_p);

    const uint32_t tohost_addr = img.tohost;

    std::cout << "[COSIM] ISA=" << cfg.isa << " priv=" << cfg.priv
              << " entry=0x" << std::hex << img.entry
              << " tohost=0x" << tohost_addr << std::dec << "\n";

    std::cout << "[COSIM] start lockstep (firmware=" << fw_path << ")\n";



    // ------------------------------------------------------------------------
    // LOCKSTEP
    // ------------------------------------------------------------------------

    reset_dut();

    uint64_t retire = 0;
    uint64_t idle = 0;

    const uint64_t IDLE_LIMIT = 200000;   // Cycles without retire: possible stall

    bool first_commit_seen = false;

    while (retire < max_retire) {

        // Advance until at least one committed event is available.
        while (g_events.empty()) {
            clk_tick();

            if (++idle > IDLE_LIMIT) {
                std::cout << "[COSIM] TIMEOUT: no retire for " << IDLE_LIMIT
                          << " cycles, possible cache/HTIF deadlock\n";
                close_and_exit(3);
            }
        }

        idle = 0;

        RvfiEvent d = g_events.front();
        g_events.pop_front();

        // Initial synchronization:
        // ignore ROM-stub retires in M-mode while PC < USER_BASE, until the
        // user program starts.
        if (!first_commit_seen) {
            if (d.pc < USER_BASE) { continue; }

            first_commit_seen = true;
        }

        // Termination: store to "tohost" through HTIF.
        // Both sides have finished.
        if (d.is_store && tohost_addr && d.mem_addr == tohost_addr) {
            std::cout << "[COSIM] tohost write detected (value=0x"
                      << std::hex << d.mem_data << std::dec << ")\n";
            std::cout << "[COSIM] PASS - " << retire
                      << " instructions compared, no mismatch.\n";

            close_and_exit((d.mem_data == 1) ? 0 : 1);
        }

        push_pc(d.pc);

        // Step the golden model.
        uint32_t spike_pc = (uint32_t)st->pc;
        insn_t insn = {};

        try {
            insn = p->get_mmu()->load_insn(st->pc).insn;
        } catch (...) {}

        try {
            p->step(1);
        } catch (trap_t& tr) {
            // Spike raised a trap, for example mtvec with unmapped address.
            // This is acceptable only if the DUT also reported an exception.
            if (!d.is_exception) {
                std::cout << "\n[COSIM][MISMATCH] @retire #" << std::dec << retire
                          << " spike trap cause=0x" << std::hex << tr.cause()
                          << " but DUT did not report an exception (PC=0x"
                          << spike_pc << ")\n";

                close_and_exit(1);
            }

            retire++;

            continue;
        } catch (...) {
            std::cout << "\n[COSIM] unknown Spike exception @retire #" << retire
                      << " PC=0x" << std::hex << spike_pc << "\n";

            close_and_exit(1);
        }

        uint32_t spike_rd  = d.rd;
        uint32_t spike_val = (d.rd != 0) ? (uint32_t)st->XPR[d.rd] : 0;


        // -------- Comparison --------
        bool ok = true;
        const char* what = "";

        if ((uint32_t)spike_pc != d.pc) {
            ok = false;
            what = "PC";
        }

        // Reg destination value.
        // CSRs are excluded: if the instruction is CSR_OPERATION, the value is
        // not compared because mcycle/minstret/etc. are expected to diverge.
        const uint32_t CSR_OPERATION = 22;
        if (ok && d.rd != 0 && d.info != CSR_OPERATION) {
            if ((uint32_t)st->XPR[d.rd] != d.rd_value) {
                ok = false;
                what = "rd value";
            }
        }


        // Memory:
        // compare address, and store data when applicable, against Spike's
        // commit log. cpu_store/load_channel provide absolute addresses
        // >= USER_BASE or the effective Spike address.
        if (ok && (d.is_store || d.is_load)) {
            const auto& log_mem = st->log_mem_write;
            const auto& log_rd  = st->log_mem_read;

            if (d.is_store && !log_mem.empty()) {
                uint32_t saddr = (uint32_t)std::get<0>(log_mem[0]);
                uint32_t sdata = (uint32_t)std::get<1>(log_mem[0]);

                // Mask data according to store width.
                // Spike already logs masked data.
                uint32_t mask = (d.mem_width == 0) ? 0xFFu
                              : (d.mem_width == 1) ? 0xFFFFu
                              : 0xFFFFFFFFu;

                uint32_t lane_shift = (d.mem_addr & 0x3) * 8;
                uint32_t dut_data   = d.mem_data >> lane_shift;

                if (saddr != d.mem_addr) {
                    ok = false;
                    what = "store addr";
                } else if ((sdata & mask) != (dut_data & mask)) {
                    ok = false;
                    what = "store data";
                }
            } else if (d.is_load && !log_rd.empty()) {
                uint32_t laddr = (uint32_t)std::get<0>(log_rd[0]);

                if (laddr != d.mem_addr) {
                    ok = false;
                    what = "load addr";
                }
            }
        }

        if (!ok) {
            report_mismatch(retire, what, d, spike_pc, spike_rd, spike_val, &dis, insn);
            close_and_exit(1);
        }

        retire++;
    }

    std::cout << "[COSIM] STOP - reached max_retire=" << std::dec << max_retire
              << " (" << retire << " compared, no mismatch).\n";
              
    close_and_exit(0);
}