#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Script generated by Vivado on Tue Aug 04 18:33:27 CEST 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : ddr_controller.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : ddr_controller.sh
#                ddr_controller.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                ddr_controller.sh [-rerun]
#                ddr_controller.sh [-reset_run]
#                ddr_controller.sh [-clean]
#                ddr_controller.sh [-reset_log]
#                ddr_controller.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'ddr_controller.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************
export SIM_VER_XCELIUM=
export GCC_VER_XCELIUM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xpm -libname xil_defaultlib -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xpm xil_defaultlib)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "ddr_controller.sh - Script generated by export_simulation (Vivado v2026.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./ddr_controller.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../../../../../../../../tools/Xilinx/2026.1/data/rsb/busdef" \
  "srcs/rtl/xpm/xpm_cdc.sv" \
  "srcs/rtl/xpm/xpm_fifo.sv" \
  "srcs/rtl/xpm/xpm_memory.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "srcs/rtl/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../../../../../../../../tools/Xilinx/2026.1/data/rsb/busdef" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ddr_controller_mig_sim.v" \
  "srcs/sources_1/ip/ddr_controller/ddr_controller/user_design/rtl/ddr_controller.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.ddr_controller xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.ddr_controller -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

  # delete previous design library generated data
  if [[ ($b_clean == 1) ]]; then
    clean
    echo -e "INFO: Design library generated data deleted.\n"
    exit 0
  fi

  # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_rerun == 1) ]]; then
    # keep previous state for incremental run
    return 0
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/gabriele/Desktop/Projects/ZenithSoC/build/vivado/project/ZenithSoC.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log ddr_controller_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated design library data from the previous run
clean()
{
  files_to_remove=("${design_libs[@]}")
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="$sim_lib_dir/${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  # delete design library directory
  rm -rf $sim_lib_dir
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./ddr_controller.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -rerun)         b_rerun=1         ;;
      -reset_run)     b_reset_run=1     ;;
      -clean)         b_clean=1         ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -clean is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_clean == 1) ]]; then
    echo -e "ERROR: -clean switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: ddr_controller.sh [-help]\n\
Usage: ddr_controller.sh [-step]\n\
Usage: ddr_controller.sh [-lib_map_path]\n\
Usage: ddr_controller.sh [-rerun]\n\
Usage: ddr_controller.sh [-reset_run]\n\
Usage: ddr_controller.sh [-clean]\n\
Usage: ddr_controller.sh [-reset_log]\n\
Usage: ddr_controller.sh [-keep_index]\n\
Usage: ddr_controller.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-rerun] -- Rerun step(s) in incremental mode (data generated from the previous run will be retained).\n\
To rerun a specific step, pass the -step <name> switch in addition to -rerun switch.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-clean] -- Delete simulator generated design library data from the previous run. This switch will not\n\
execute steps defined in the script.\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_rerun=0
b_reset_run=0
b_clean=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
